export interface Weapon {
  id: string;
  name: string;
  namePt?: string;
  nameEn?: string;
  type: "Assault Rifle" | "Sniper" | "SMG" | "Shotgun" | "LMG" | "Marksman" | "Pistol";
  description: string;
  descriptionEn?: string;
  code: string;
  codePt?: string;
  codeEn?: string;
  image?: string;
  imagePt?: string;
  imageEn?: string;
  keywords?: string[];
}

export const weaponsData: Weapon[] = [
  // SNIPERS / FRANCO-ATIRADORES
  {
    id: "outlaw",
    name: "Outlaw",
    namePt: "Outlaw",
    nameEn: "Outlaw",
    type: "Sniper",
    description: "Franco-atirador rápido e preciso",
    descriptionEn: "Fast and precise sniper",
    code: "2A4C5H6A9C",
    codePt: "2A4C5H6A9C",
    codeEn: "2A4C5H6A9C",
    imagePt: "/attached_assets/1000004329.jpg",
    imageEn: "/attached_assets/1000004335.jpg",
    image: "/attached_assets/1000004329.jpg",
    keywords: ["outlaw", "sniper", "franco-atirador"]
  },
  {
    id: "koshka",
    name: "Koshka",
    namePt: "Koshka",
    nameEn: "Koshka",
    type: "Sniper",
    description: "Franco-atirador com grande poder de fogo",
    descriptionEn: "Sniper with great firepower",
    code: "2A4A5G6A9C",
    codePt: "2A4A5G6A9C",
    codeEn: "2A4A5G6A9C",
    imagePt: "/attached_assets/1000004330.jpg",
    imageEn: "/attached_assets/1000004336.jpg",
    image: "/attached_assets/1000004330.jpg",
    keywords: ["koshka", "sniper", "franco-atirador"]
  },
  {
    id: "three-line-rifle",
    name: "3-Line Rifle",
    namePt: "Fuzil de 3 Linhas",
    nameEn: "3-Line Rifle",
    type: "Sniper",
    description: "Franco-atirador versátil e eficaz",
    descriptionEn: "Versatile and effective sniper",
    code: "1E2A4B5F",
    codePt: "1E2A4B5F",
    codeEn: "1E2A4B5F",
    imagePt: "/attached_assets/1000004331.jpg",
    imageEn: "/attached_assets/1000004337.jpg",
    image: "/attached_assets/1000004331.jpg",
    keywords: ["fuzil", "3 linhas", "three line", "rifle", "sniper", "franco-atirador"]
  },
  {
    id: "locus",
    name: "Locus",
    namePt: "Locus",
    nameEn: "Locus",
    type: "Sniper",
    description: "Franco-atirador equilibrado e confiável",
    descriptionEn: "Balanced and reliable sniper",
    code: "2A4B5H8C9C",
    codePt: "2A4B5H8C9C",
    codeEn: "2A4B5H8C9C",
    imagePt: "/attached_assets/1000004332.jpg",
    imageEn: "/attached_assets/1000004339.jpg",
    image: "/attached_assets/1000004332.jpg",
    keywords: ["locus", "sniper", "franco-atirador"]
  },
  {
    id: "dlq33",
    name: "DL Q33",
    namePt: "DL Q33",
    nameEn: "DL Q33",
    type: "Sniper",
    description: "Franco-atirador de alto dano",
    descriptionEn: "High damage sniper",
    code: "2A4A5A6A8A",
    codePt: "2A4A5A6A8A",
    codeEn: "2A4A5A6A8A",
    imagePt: "/attached_assets/1000004333.jpg",
    imageEn: "/attached_assets/1000004340.jpg",
    image: "/attached_assets/1000004333.jpg",
    keywords: ["dlq", "dl q33", "dlq33", "sniper", "franco-atirador"]
  },
  {
    id: "lw3-tundra",
    name: "LW3-Tundra",
    namePt: "LW3-Tundra",
    nameEn: "LW3-Tundra",
    type: "Sniper",
    description: "Franco-atirador moderno e poderoso",
    descriptionEn: "Modern and powerful sniper",
    code: "1A2F5A8A9E",
    codePt: "1A2F5A8A9E",
    codeEn: "1A2F5A8A9E",
    imagePt: "/attached_assets/1000004334.jpg",
    imageEn: "/attached_assets/1000004338.jpg",
    image: "/attached_assets/1000004334.jpg",
    keywords: ["lw3", "tundra", "lw3-tundra", "sniper", "franco-atirador"]
  },

  // SMG / SUBMETRALHADORAS
  {
    id: "cx9",
    name: "CX-9",
    namePt: "CX-9",
    nameEn: "CX-9",
    type: "SMG",
    description: "Submetralhadora rápida e ágil",
    descriptionEn: "Fast and agile submachine gun",
    code: "1A2B4C8B9A",
    codePt: "1A2B4C8B9A",
    codeEn: "1A2B4C8B9A",
    imagePt: "/attached_assets/1000004501.jpg",
    imageEn: "/attached_assets/1000004508.jpg",
    image: "/attached_assets/1000004501.jpg",
    keywords: ["cx9", "cx-9", "smt", "smg", "submetralhadora"]
  },
  {
    id: "vmp",
    name: "VMP",
    namePt: "VMP",
    nameEn: "VMP",
    type: "SMG",
    description: "Submetralhadora com taxa de fogo alta",
    descriptionEn: "Submachine gun with high fire rate",
    code: "2D4C5H8A9C",
    codePt: "2D4C5H8A9C",
    codeEn: "2D4C5H8A9C",
    imagePt: "/attached_assets/1000004503.jpg",
    imageEn: "/attached_assets/1000004510.jpg",
    image: "/attached_assets/1000004503.jpg",
    keywords: ["vmp", "smt", "smg", "submetralhadora"]
  },
  {
    id: "switchblade-x9",
    name: "Switchblade X9",
    namePt: "Switchblade X9",
    nameEn: "Switchblade X9",
    type: "SMG",
    description: "Submetralhadora compacta e mortífera",
    descriptionEn: "Compact and deadly submachine gun",
    code: "1A2C4C8A9A",
    codePt: "1A2C4C8A9A",
    codeEn: "1A2C4C8A9A",
    imagePt: "/attached_assets/1000004505.jpg",
    imageEn: "/attached_assets/1000004512.jpg",
    image: "/attached_assets/1000004505.jpg",
    keywords: ["switchblade", "x9", "smt", "smg", "submetralhadora"]
  },
  {
    id: "mx9",
    name: "MX9",
    namePt: "MX9",
    nameEn: "MX9",
    type: "SMG",
    description: "Submetralhadora versátil para combate próximo",
    descriptionEn: "Versatile submachine gun for close combat",
    code: "1B2A4D6C8B",
    codePt: "1B2A4D6C8B",
    codeEn: "1B2A4D6C8B",
    imagePt: "/attached_assets/1000004519.jpg",
    imageEn: "/attached_assets/1000004515.jpg",
    image: "/attached_assets/1000004519.jpg",
    keywords: ["mx9", "mx-9", "smt", "smg", "submetralhadora"]
  },

  // ASSAULT / ASSALTO
  {
    id: "type19",
    name: "Type 19",
    namePt: "Type 19",
    nameEn: "Type 19",
    type: "Assault Rifle",
    description: "Rifle de assalto equilibrado",
    descriptionEn: "Balanced assault rifle",
    code: "1D4A7B8B9C",
    codePt: "1D4A7B8B9C",
    codeEn: "1D4A7B8B9C",
    imagePt: "/attached_assets/1000004502.jpg",
    imageEn: "/attached_assets/1000004509.jpg",
    image: "/attached_assets/1000004502.jpg",
    keywords: ["type19", "type 19", "assalto", "assault", "rifle"]
  },
  {
    id: "xm4",
    name: "XM4",
    namePt: "XM4",
    nameEn: "XM4",
    type: "Assault Rifle",
    description: "Rifle de assalto com baixo recuo",
    descriptionEn: "Assault rifle with low recoil",
    code: "1A2G4A7C8D",
    codePt: "1A2G4A7C8D",
    codeEn: "1A2G4A7C8D",
    imagePt: "/attached_assets/1000004504.jpg",
    imageEn: "/attached_assets/1000004511.jpg",
    image: "/attached_assets/1000004504.jpg",
    keywords: ["xm4", "xm-4", "assalto", "assault", "rifle"]
  },
  {
    id: "drh",
    name: "DR-H",
    namePt: "DR-H",
    nameEn: "DR-H",
    type: "Assault Rifle",
    description: "Rifle de assalto poderoso",
    descriptionEn: "Powerful assault rifle",
    code: "1A2B4A8C9A",
    codePt: "1A2B4A8C9A",
    codeEn: "1A2B4A8C9A",
    imagePt: "/attached_assets/1000004506.jpg",
    imageEn: "/attached_assets/1000004513.jpg",
    image: "/attached_assets/1000004506.jpg",
    keywords: ["drh", "dr-h", "assalto", "assault", "rifle"]
  },
  {
    id: "oden",
    name: "Oden",
    namePt: "Oden",
    nameEn: "Oden",
    type: "Assault Rifle",
    description: "Rifle de assalto de alto dano",
    descriptionEn: "High damage assault rifle",
    code: "1A4A5A7C9A",
    codePt: "1A4A5A7C9A",
    codeEn: "1A4A5A7C9A",
    imagePt: "/attached_assets/1000004521.jpg",
    imageEn: "/attached_assets/1000004517.jpg",
    image: "/attached_assets/1000004521.jpg",
    keywords: ["oden", "assalto", "assault", "rifle"]
  },

  // SHOTGUN / ESCOPETA
  {
    id: "hs0405",
    name: "HS0405",
    namePt: "HS0405",
    nameEn: "HS0405",
    type: "Shotgun",
    description: "Escopeta com alta mobilidade",
    descriptionEn: "Shotgun with high mobility",
    code: "1F2A4A5E6A",
    codePt: "1F2A4A5E6A",
    codeEn: "1F2A4A5E6A",
    imagePt: "/attached_assets/1000004507.jpg",
    imageEn: "/attached_assets/1000004514.jpg",
    image: "/attached_assets/1000004507.jpg",
    keywords: ["hs0405", "hs", "escopeta", "shotgun"]
  },
  {
    id: "by15",
    name: "BY15",
    namePt: "BY15",
    nameEn: "BY15",
    type: "Shotgun",
    description: "Escopeta de disparo rápido",
    descriptionEn: "Fast-firing shotgun",
    code: "1C2A3A4A8B",
    codePt: "1C2A3A4A8B",
    codeEn: "1C2A3A4A8B",
    imagePt: "/attached_assets/1000004520.jpg",
    imageEn: "/attached_assets/1000004516.jpg",
    image: "/attached_assets/1000004520.jpg",
    keywords: ["by15", "by", "escopeta", "shotgun"]
  },

  // MARKSMAN / ATIRADOR
  {
    id: "type63",
    name: "Type 63",
    namePt: "Type 63",
    nameEn: "Type 63",
    type: "Marksman",
    description: "Rifle de precisão de médio alcance",
    descriptionEn: "Medium-range precision rifle",
    code: "1C2B4A7E9F",
    codePt: "1C2B4A7E9F",
    codeEn: "1C2B4A7E9F",
    imagePt: "/attached_assets/1000004522.jpg",
    imageEn: "/attached_assets/1000004518.jpg",
    image: "/attached_assets/1000004522.jpg",
    keywords: ["type63", "type 63", "atirador", "marksman"]
  },
  {
    id: "chicom",
    name: "Chicom",
    namePt: "Chicom",
    nameEn: "Chicom",
    type: "SMG",
    description: "Melhor classe para Chicom no COD Mobile",
    descriptionEn: "Best loadout for Chicom in COD Mobile",
    code: "1C2B3A4A8C",
    codePt: "1C2B3A4A8C",
    codeEn: "1C2B3A4A8C",
    image: "/attached_assets/chicom.jpg",
    imagePt: "/attached_assets/chicom.jpg",
    imageEn: "/attached_assets/chicom.jpg",
    keywords: ["chicom", "smg", "codm", "loadout"],
  },
  {
    id: "pp19-bizon",
    name: "PP19 Bizon",
    namePt: "PP19 Bizon",
    nameEn: "PP19 Bizon",
    type: "SMG",
    description: "Melhor classe para PP19 Bizon no COD Mobile",
    descriptionEn: "Best loadout for PP19 Bizon in COD Mobile",
    code: "1C2B4A6C9A",
    codePt: "1C2B4A6C9A",
    codeEn: "1C2B4A6C9A",
    image: "/attached_assets/pp19-bizon.jpg",
    imagePt: "/attached_assets/pp19-bizon.jpg",
    imageEn: "/attached_assets/pp19-bizon.jpg",
    keywords: ["pp19-bizon", "smg", "codm", "loadout"],
  },
  {
    id: "m13",
    name: "M13",
    namePt: "M13",
    nameEn: "M13",
    type: "Assault Rifle",
    description: "Melhor classe para M13 no COD Mobile",
    descriptionEn: "Best loadout for M13 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/m13.jpg",
    imagePt: "/attached_assets/m13.jpg",
    imageEn: "/attached_assets/m13.jpg",
    keywords: ["m13", "assault rifle", "codm", "loadout"],
  },
  {
    id: "kilo-141",
    name: "Kilo 141",
    namePt: "Kilo 141",
    nameEn: "Kilo 141",
    type: "Assault Rifle",
    description: "Melhor classe para Kilo 141 no COD Mobile",
    descriptionEn: "Best loadout for Kilo 141 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/kilo-141.jpg",
    imagePt: "/attached_assets/kilo-141.jpg",
    imageEn: "/attached_assets/kilo-141.jpg",
    keywords: ["kilo-141", "assault rifle", "codm", "loadout"],
  },
  {
    id: "m4",
    name: "M4",
    namePt: "M4",
    nameEn: "M4",
    type: "Assault Rifle",
    description: "Melhor classe para M4 no COD Mobile",
    descriptionEn: "Best loadout for M4 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/m4.jpg",
    imagePt: "/attached_assets/m4.jpg",
    imageEn: "/attached_assets/m4.jpg",
    keywords: ["m4", "assault rifle", "codm", "loadout"],
  },
  {
    id: "ak-47",
    name: "AK-47",
    namePt: "AK-47",
    nameEn: "AK-47",
    type: "Assault Rifle",
    description: "Melhor classe para AK-47 no COD Mobile",
    descriptionEn: "Best loadout for AK-47 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/ak-47.jpg",
    imagePt: "/attached_assets/ak-47.jpg",
    imageEn: "/attached_assets/ak-47.jpg",
    keywords: ["ak-47", "assault rifle", "codm", "loadout"],
  },
  {
    id: "dr-h",
    name: "DR-H",
    namePt: "DR-H",
    nameEn: "DR-H",
    type: "Assault Rifle",
    description: "Melhor classe para DR-H no COD Mobile",
    descriptionEn: "Best loadout for DR-H in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/dr-h.jpg",
    imagePt: "/attached_assets/dr-h.jpg",
    imageEn: "/attached_assets/dr-h.jpg",
    keywords: ["dr-h", "assault rifle", "codm", "loadout"],
  },
  {
    id: "hvk-30",
    name: "HVK-30",
    namePt: "HVK-30",
    nameEn: "HVK-30",
    type: "Assault Rifle",
    description: "Melhor classe para HVK-30 no COD Mobile",
    descriptionEn: "Best loadout for HVK-30 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/hvk-30.jpg",
    imagePt: "/attached_assets/hvk-30.jpg",
    imageEn: "/attached_assets/hvk-30.jpg",
    keywords: ["hvk-30", "assault rifle", "codm", "loadout"],
  },
  {
    id: "kn-44",
    name: "KN-44",
    namePt: "KN-44",
    nameEn: "KN-44",
    type: "Assault Rifle",
    description: "Melhor classe para KN-44 no COD Mobile",
    descriptionEn: "Best loadout for KN-44 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/kn-44.jpg",
    imagePt: "/attached_assets/kn-44.jpg",
    imageEn: "/attached_assets/kn-44.jpg",
    keywords: ["kn-44", "assault rifle", "codm", "loadout"],
  },
  {
    id: "icr-1",
    name: "ICR-1",
    namePt: "ICR-1",
    nameEn: "ICR-1",
    type: "Assault Rifle",
    description: "Melhor classe para ICR-1 no COD Mobile",
    descriptionEn: "Best loadout for ICR-1 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/icr-1.jpg",
    imagePt: "/attached_assets/icr-1.jpg",
    imageEn: "/attached_assets/icr-1.jpg",
    keywords: ["icr-1", "assault rifle", "codm", "loadout"],
  },
  {
    id: "man-o-war",
    name: "Man-O-War",
    namePt: "Man-O-War",
    nameEn: "Man-O-War",
    type: "Assault Rifle",
    description: "Melhor classe para Man-O-War no COD Mobile",
    descriptionEn: "Best loadout for Man-O-War in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/man-o-war.jpg",
    imagePt: "/attached_assets/man-o-war.jpg",
    imageEn: "/attached_assets/man-o-war.jpg",
    keywords: ["man-o-war", "assault rifle", "codm", "loadout"],
  },
  {
    id: "as-val",
    name: "AS VAL",
    namePt: "AS VAL",
    nameEn: "AS VAL",
    type: "Assault Rifle",
    description: "Melhor classe para AS VAL no COD Mobile",
    descriptionEn: "Best loadout for AS VAL in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/as-val.jpg",
    imagePt: "/attached_assets/as-val.jpg",
    imageEn: "/attached_assets/as-val.jpg",
    keywords: ["as-val", "assault rifle", "codm", "loadout"],
  },
  {
    id: "bk57",
    name: "BK57",
    namePt: "BK57",
    nameEn: "BK57",
    type: "Assault Rifle",
    description: "Melhor classe para BK57 no COD Mobile",
    descriptionEn: "Best loadout for BK57 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/bk57.jpg",
    imagePt: "/attached_assets/bk57.jpg",
    imageEn: "/attached_assets/bk57.jpg",
    keywords: ["bk57", "assault rifle", "codm", "loadout"],
  },
  {
    id: "lk24",
    name: "LK24",
    namePt: "LK24",
    nameEn: "LK24",
    type: "Assault Rifle",
    description: "Melhor classe para LK24 no COD Mobile",
    descriptionEn: "Best loadout for LK24 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/lk24.jpg",
    imagePt: "/attached_assets/lk24.jpg",
    imageEn: "/attached_assets/lk24.jpg",
    keywords: ["lk24", "assault rifle", "codm", "loadout"],
  },
  {
    id: "peacekeeper-mk2",
    name: "Peacekeeper MK2",
    namePt: "Peacekeeper MK2",
    nameEn: "Peacekeeper MK2",
    type: "Assault Rifle",
    description: "Melhor classe para Peacekeeper MK2 no COD Mobile",
    descriptionEn: "Best loadout for Peacekeeper MK2 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/peacekeeper-mk2.jpg",
    imagePt: "/attached_assets/peacekeeper-mk2.jpg",
    imageEn: "/attached_assets/peacekeeper-mk2.jpg",
    keywords: ["peacekeeper-mk2", "assault rifle", "codm", "loadout"],
  },
  {
    id: "fr-5-56",
    name: "FR 5.56",
    namePt: "FR 5.56",
    nameEn: "FR 5.56",
    type: "Assault Rifle",
    description: "Melhor classe para FR 5.56 no COD Mobile",
    descriptionEn: "Best loadout for FR 5.56 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/fr-5-56.jpg",
    imagePt: "/attached_assets/fr-5-56.jpg",
    imageEn: "/attached_assets/fr-5-56.jpg",
    keywords: ["fr-5-56", "assault rifle", "codm", "loadout"],
  },
  {
    id: "hbra3",
    name: "HBRa3",
    namePt: "HBRa3",
    nameEn: "HBRa3",
    type: "Assault Rifle",
    description: "Melhor classe para HBRa3 no COD Mobile",
    descriptionEn: "Best loadout for HBRa3 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/hbra3.jpg",
    imagePt: "/attached_assets/hbra3.jpg",
    imageEn: "/attached_assets/hbra3.jpg",
    keywords: ["hbra3", "assault rifle", "codm", "loadout"],
  },
  {
    id: "ak117",
    name: "AK117",
    namePt: "AK117",
    nameEn: "AK117",
    type: "Assault Rifle",
    description: "Melhor classe para AK117 no COD Mobile",
    descriptionEn: "Best loadout for AK117 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/ak117.jpg",
    imagePt: "/attached_assets/ak117.jpg",
    imageEn: "/attached_assets/ak117.jpg",
    keywords: ["ak117", "assault rifle", "codm", "loadout"],
  },
  {
    id: "type-25",
    name: "Type 25",
    namePt: "Type 25",
    nameEn: "Type 25",
    type: "Assault Rifle",
    description: "Melhor classe para Type 25 no COD Mobile",
    descriptionEn: "Best loadout for Type 25 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/type-25.jpg",
    imagePt: "/attached_assets/type-25.jpg",
    imageEn: "/attached_assets/type-25.jpg",
    keywords: ["type-25", "assault rifle", "codm", "loadout"],
  },
  {
    id: "asm10",
    name: "ASM10",
    namePt: "ASM10",
    nameEn: "ASM10",
    type: "Assault Rifle",
    description: "Melhor classe para ASM10 no COD Mobile",
    descriptionEn: "Best loadout for ASM10 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/asm10.jpg",
    imagePt: "/attached_assets/asm10.jpg",
    imageEn: "/attached_assets/asm10.jpg",
    keywords: ["asm10", "assault rifle", "codm", "loadout"],
  },
  {
    id: "dl-q33",
    name: "DL Q33",
    namePt: "DL Q33",
    nameEn: "DL Q33",
    type: "Sniper",
    description: "Melhor classe para DL Q33 no COD Mobile",
    descriptionEn: "Best loadout for DL Q33 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/dl-q33.jpg",
    imagePt: "/attached_assets/dl-q33.jpg",
    imageEn: "/attached_assets/dl-q33.jpg",
    keywords: ["dl-q33", "sniper", "codm", "loadout"],
  },
  {
    id: "locus-2",
    name: "Locus",
    namePt: "Locus",
    nameEn: "Locus",
    type: "Sniper",
    description: "Melhor classe para Locus no COD Mobile",
    descriptionEn: "Best loadout for Locus in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/locus.jpg",
    imagePt: "/attached_assets/locus.jpg",
    imageEn: "/attached_assets/locus.jpg",
    keywords: ["locus", "sniper", "codm", "loadout"],
  },
  {
    id: "arctic-50",
    name: "Arctic .50",
    namePt: "Arctic .50",
    nameEn: "Arctic .50",
    type: "Sniper",
    description: "Melhor classe para Arctic .50 no COD Mobile",
    descriptionEn: "Best loadout for Arctic .50 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/arctic-50.jpg",
    imagePt: "/attached_assets/arctic-50.jpg",
    imageEn: "/attached_assets/arctic-50.jpg",
    keywords: ["arctic-50", "sniper", "codm", "loadout"],
  },
  {
    id: "koshka-2",
    name: "Koshka",
    namePt: "Koshka",
    nameEn: "Koshka",
    type: "Sniper",
    description: "Melhor classe para Koshka no COD Mobile",
    descriptionEn: "Best loadout for Koshka in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/koshka.jpg",
    imagePt: "/attached_assets/koshka.jpg",
    imageEn: "/attached_assets/koshka.jpg",
    keywords: ["koshka", "sniper", "codm", "loadout"],
  },
  {
    id: "zrg-20mm",
    name: "ZRG 20mm",
    namePt: "ZRG 20mm",
    nameEn: "ZRG 20mm",
    type: "Sniper",
    description: "Melhor classe para ZRG 20mm no COD Mobile",
    descriptionEn: "Best loadout for ZRG 20mm in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/zrg-20mm.jpg",
    imagePt: "/attached_assets/zrg-20mm.jpg",
    imageEn: "/attached_assets/zrg-20mm.jpg",
    keywords: ["zrg-20mm", "sniper", "codm", "loadout"],
  },
  {
    id: "sks",
    name: "SKS",
    namePt: "SKS",
    nameEn: "SKS",
    type: "Marksman",
    description: "Melhor classe para SKS no COD Mobile",
    descriptionEn: "Best loadout for SKS in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/sks.jpg",
    imagePt: "/attached_assets/sks.jpg",
    imageEn: "/attached_assets/sks.jpg",
    keywords: ["sks", "marksman", "codm", "loadout"],
  },
  {
    id: "mk2",
    name: "MK2",
    namePt: "MK2",
    nameEn: "MK2",
    type: "Marksman",
    description: "Melhor classe para MK2 no COD Mobile",
    descriptionEn: "Best loadout for MK2 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/mk2.jpg",
    imagePt: "/attached_assets/mk2.jpg",
    imageEn: "/attached_assets/mk2.jpg",
    keywords: ["mk2", "marksman", "codm", "loadout"],
  },
  {
    id: "kilo-bolt-action",
    name: "Kilo Bolt-Action",
    namePt: "Kilo Bolt-Action",
    nameEn: "Kilo Bolt-Action",
    type: "Marksman",
    description: "Melhor classe para Kilo Bolt-Action no COD Mobile",
    descriptionEn: "Best loadout for Kilo Bolt-Action in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/kilo-bolt-action.jpg",
    imagePt: "/attached_assets/kilo-bolt-action.jpg",
    imageEn: "/attached_assets/kilo-bolt-action.jpg",
    keywords: ["kilo-bolt-action", "marksman", "codm", "loadout"],
  },
  {
    id: "sp-r-208",
    name: "SP-R 208",
    namePt: "SP-R 208",
    nameEn: "SP-R 208",
    type: "Marksman",
    description: "Melhor classe para SP-R 208 no COD Mobile",
    descriptionEn: "Best loadout for SP-R 208 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/sp-r-208.jpg",
    imagePt: "/attached_assets/sp-r-208.jpg",
    imageEn: "/attached_assets/sp-r-208.jpg",
    keywords: ["sp-r-208", "marksman", "codm", "loadout"],
  },
  {
    id: "kar98k",
    name: "Kar98k",
    namePt: "Kar98k",
    nameEn: "Kar98k",
    type: "Assault Rifle",
    description: "Melhor classe para Kar98k no COD Mobile",
    descriptionEn: "Best loadout for Kar98k in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/kar98k.jpg",
    imagePt: "/attached_assets/kar98k.jpg",
    imageEn: "/attached_assets/kar98k.jpg",
    keywords: ["kar98k", "assault rifle", "codm", "loadout"],
  },
  {
    id: "outlaw-2",
    name: "Outlaw",
    namePt: "Outlaw",
    nameEn: "Outlaw",
    type: "Sniper",
    description: "Melhor classe para Outlaw no COD Mobile",
    descriptionEn: "Best loadout for Outlaw in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/outlaw.jpg",
    imagePt: "/attached_assets/outlaw.jpg",
    imageEn: "/attached_assets/outlaw.jpg",
    keywords: ["outlaw", "sniper", "codm", "loadout"],
  },
  {
    id: "m21-ebr",
    name: "M21 EBR",
    namePt: "M21 EBR",
    nameEn: "M21 EBR",
    type: "Sniper",
    description: "Melhor classe para M21 EBR no COD Mobile",
    descriptionEn: "Best loadout for M21 EBR in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/m21-ebr.jpg",
    imagePt: "/attached_assets/m21-ebr.jpg",
    imageEn: "/attached_assets/m21-ebr.jpg",
    keywords: ["m21-ebr", "sniper", "codm", "loadout"],
  },
  {
    id: "xpr-50",
    name: "XPR-50",
    namePt: "XPR-50",
    nameEn: "XPR-50",
    type: "Sniper",
    description: "Melhor classe para XPR-50 no COD Mobile",
    descriptionEn: "Best loadout for XPR-50 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/xpr-50.jpg",
    imagePt: "/attached_assets/xpr-50.jpg",
    imageEn: "/attached_assets/xpr-50.jpg",
    keywords: ["xpr-50", "sniper", "codm", "loadout"],
  },
  {
    id: "na-45",
    name: "NA-45",
    namePt: "NA-45",
    nameEn: "NA-45",
    type: "Sniper",
    description: "Melhor classe para NA-45 no COD Mobile",
    descriptionEn: "Best loadout for NA-45 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/na-45.jpg",
    imagePt: "/attached_assets/na-45.jpg",
    imageEn: "/attached_assets/na-45.jpg",
    keywords: ["na-45", "sniper", "codm", "loadout"],
  },
  {
    id: "d-13-sector",
    name: "D-13 Sector",
    namePt: "D-13 Sector",
    nameEn: "D-13 Sector",
    type: "Assault Rifle",
    description: "Melhor classe para D-13 Sector no COD Mobile",
    descriptionEn: "Best loadout for D-13 Sector in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/d-13-sector.jpg",
    imagePt: "/attached_assets/d-13-sector.jpg",
    imageEn: "/attached_assets/d-13-sector.jpg",
    keywords: ["d-13-sector", "assault rifle", "codm", "loadout"],
  },
  {
    id: "svd",
    name: "SVD",
    namePt: "SVD",
    nameEn: "SVD",
    type: "Sniper",
    description: "Melhor classe para SVD no COD Mobile",
    descriptionEn: "Best loadout for SVD in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/svd.jpg",
    imagePt: "/attached_assets/svd.jpg",
    imageEn: "/attached_assets/svd.jpg",
    keywords: ["svd", "sniper", "codm", "loadout"],
  },
  {
    id: "r9-0",
    name: "R9-0",
    namePt: "R9-0",
    nameEn: "R9-0",
    type: "Shotgun",
    description: "Melhor classe para R9-0 no COD Mobile",
    descriptionEn: "Best loadout for R9-0 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/r9-0.jpg",
    imagePt: "/attached_assets/r9-0.jpg",
    imageEn: "/attached_assets/r9-0.jpg",
    keywords: ["r9-0", "shotgun", "codm", "loadout"],
  },
  {
    id: "krm-262",
    name: "KRM-262",
    namePt: "KRM-262",
    nameEn: "KRM-262",
    type: "Shotgun",
    description: "Melhor classe para KRM-262 no COD Mobile",
    descriptionEn: "Best loadout for KRM-262 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/krm-262.jpg",
    imagePt: "/attached_assets/krm-262.jpg",
    imageEn: "/attached_assets/krm-262.jpg",
    keywords: ["krm-262", "shotgun", "codm", "loadout"],
  },
  {
    id: "by15-2",
    name: "BY15",
    namePt: "BY15",
    nameEn: "BY15",
    type: "Shotgun",
    description: "Melhor classe para BY15 no COD Mobile",
    descriptionEn: "Best loadout for BY15 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/by15.jpg",
    imagePt: "/attached_assets/by15.jpg",
    imageEn: "/attached_assets/by15.jpg",
    keywords: ["by15", "shotgun", "codm", "loadout"],
  },
  {
    id: "hs0405-2",
    name: "HS0405",
    namePt: "HS0405",
    nameEn: "HS0405",
    type: "Shotgun",
    description: "Melhor classe para HS0405 no COD Mobile",
    descriptionEn: "Best loadout for HS0405 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/hs0405.jpg",
    imagePt: "/attached_assets/hs0405.jpg",
    imageEn: "/attached_assets/hs0405.jpg",
    keywords: ["hs0405", "shotgun", "codm", "loadout"],
  },
  {
    id: "hs2126",
    name: "HS2126",
    namePt: "HS2126",
    nameEn: "HS2126",
    type: "Shotgun",
    description: "Melhor classe para HS2126 no COD Mobile",
    descriptionEn: "Best loadout for HS2126 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/hs2126.jpg",
    imagePt: "/attached_assets/hs2126.jpg",
    imageEn: "/attached_assets/hs2126.jpg",
    keywords: ["hs2126", "shotgun", "codm", "loadout"],
  },
  {
    id: "echo",
    name: "Echo",
    namePt: "Echo",
    nameEn: "Echo",
    type: "Shotgun",
    description: "Melhor classe para Echo no COD Mobile",
    descriptionEn: "Best loadout for Echo in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/echo.jpg",
    imagePt: "/attached_assets/echo.jpg",
    imageEn: "/attached_assets/echo.jpg",
    keywords: ["echo", "shotgun", "codm", "loadout"],
  },
  {
    id: "striker",
    name: "Striker",
    namePt: "Striker",
    nameEn: "Striker",
    type: "Shotgun",
    description: "Melhor classe para Striker no COD Mobile",
    descriptionEn: "Best loadout for Striker in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/striker.jpg",
    imagePt: "/attached_assets/striker.jpg",
    imageEn: "/attached_assets/striker.jpg",
    keywords: ["striker", "shotgun", "codm", "loadout"],
  },
  {
    id: "jak-12",
    name: "JAK-12",
    namePt: "JAK-12",
    nameEn: "JAK-12",
    type: "Shotgun",
    description: "Melhor classe para JAK-12 no COD Mobile",
    descriptionEn: "Best loadout for JAK-12 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/jak-12.jpg",
    imagePt: "/attached_assets/jak-12.jpg",
    imageEn: "/attached_assets/jak-12.jpg",
    keywords: ["jak-12", "shotgun", "codm", "loadout"],
  },
  {
    id: "hs405",
    name: "HS405",
    namePt: "HS405",
    nameEn: "HS405",
    type: "Assault Rifle",
    description: "Melhor classe para HS405 no COD Mobile",
    descriptionEn: "Best loadout for HS405 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/hs405.jpg",
    imagePt: "/attached_assets/hs405.jpg",
    imageEn: "/attached_assets/hs405.jpg",
    keywords: ["hs405", "assault rifle", "codm", "loadout"],
  },
  {
    id: "m16",
    name: "M16",
    namePt: "M16",
    nameEn: "M16",
    type: "Assault Rifle",
    description: "Melhor classe para M16 no COD Mobile",
    descriptionEn: "Best loadout for M16 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/m16.jpg",
    imagePt: "/attached_assets/m16.jpg",
    imageEn: "/attached_assets/m16.jpg",
    keywords: ["m16", "assault rifle", "codm", "loadout"],
  },
  {
    id: "swordfish",
    name: "Swordfish",
    namePt: "Swordfish",
    nameEn: "Swordfish",
    type: "Assault Rifle",
    description: "Melhor classe para Swordfish no COD Mobile",
    descriptionEn: "Best loadout for Swordfish in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/swordfish.jpg",
    imagePt: "/attached_assets/swordfish.jpg",
    imageEn: "/attached_assets/swordfish.jpg",
    keywords: ["swordfish", "assault rifle", "codm", "loadout"],
  },
  {
    id: "agr-556",
    name: "AGR 556",
    namePt: "AGR 556",
    nameEn: "AGR 556",
    type: "SMG",
    description: "Melhor classe para AGR 556 no COD Mobile",
    descriptionEn: "Best loadout for AGR 556 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/agr-556.jpg",
    imagePt: "/attached_assets/agr-556.jpg",
    imageEn: "/attached_assets/agr-556.jpg",
    keywords: ["agr-556", "smg", "codm", "loadout"],
  },
  {
    id: "m4lmg",
    name: "M4LMG",
    namePt: "M4LMG",
    nameEn: "M4LMG",
    type: "Assault Rifle",
    description: "Melhor classe para M4LMG no COD Mobile",
    descriptionEn: "Best loadout for M4LMG in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/m4lmg.jpg",
    imagePt: "/attached_assets/m4lmg.jpg",
    imageEn: "/attached_assets/m4lmg.jpg",
    keywords: ["m4lmg", "assault rifle", "codm", "loadout"],
  },
  {
    id: "rpd",
    name: "RPD",
    namePt: "RPD",
    nameEn: "RPD",
    type: "LMG",
    description: "Melhor classe para RPD no COD Mobile",
    descriptionEn: "Best loadout for RPD in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/rpd.jpg",
    imagePt: "/attached_assets/rpd.jpg",
    imageEn: "/attached_assets/rpd.jpg",
    keywords: ["rpd", "lmg", "codm", "loadout"],
  },
  {
    id: "chopper",
    name: "Chopper",
    namePt: "Chopper",
    nameEn: "Chopper",
    type: "LMG",
    description: "Melhor classe para Chopper no COD Mobile",
    descriptionEn: "Best loadout for Chopper in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/chopper.jpg",
    imagePt: "/attached_assets/chopper.jpg",
    imageEn: "/attached_assets/chopper.jpg",
    keywords: ["chopper", "lmg", "codm", "loadout"],
  },
  {
    id: "ul736",
    name: "UL736",
    namePt: "UL736",
    nameEn: "UL736",
    type: "LMG",
    description: "Melhor classe para UL736 no COD Mobile",
    descriptionEn: "Best loadout for UL736 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/ul736.jpg",
    imagePt: "/attached_assets/ul736.jpg",
    imageEn: "/attached_assets/ul736.jpg",
    keywords: ["ul736", "lmg", "codm", "loadout"],
  },
  {
    id: "hades",
    name: "Hades",
    namePt: "Hades",
    nameEn: "Hades",
    type: "LMG",
    description: "Melhor classe para Hades no COD Mobile",
    descriptionEn: "Best loadout for Hades in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/hades.jpg",
    imagePt: "/attached_assets/hades.jpg",
    imageEn: "/attached_assets/hades.jpg",
    keywords: ["hades", "lmg", "codm", "loadout"],
  },
  {
    id: "holger-26",
    name: "Holger 26",
    namePt: "Holger 26",
    nameEn: "Holger 26",
    type: "Assault Rifle",
    description: "Melhor classe para Holger 26 no COD Mobile",
    descriptionEn: "Best loadout for Holger 26 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/holger-26.jpg",
    imagePt: "/attached_assets/holger-26.jpg",
    imageEn: "/attached_assets/holger-26.jpg",
    keywords: ["holger-26", "assault rifle", "codm", "loadout"],
  },
  {
    id: "dingo",
    name: "Dingo",
    namePt: "Dingo",
    nameEn: "Dingo",
    type: "LMG",
    description: "Melhor classe para Dingo no COD Mobile",
    descriptionEn: "Best loadout for Dingo in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/dingo.jpg",
    imagePt: "/attached_assets/dingo.jpg",
    imageEn: "/attached_assets/dingo.jpg",
    keywords: ["dingo", "lmg", "codm", "loadout"],
  },
  {
    id: "gks",
    name: "GKS",
    namePt: "GKS",
    nameEn: "GKS",
    type: "SMG",
    description: "Melhor classe para GKS no COD Mobile",
    descriptionEn: "Best loadout for GKS in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/gks.jpg",
    imagePt: "/attached_assets/gks.jpg",
    imageEn: "/attached_assets/gks.jpg",
    keywords: ["gks", "smg", "codm", "loadout"],
  },
  {
    id: "pdw-57",
    name: "PDW-57",
    namePt: "PDW-57",
    nameEn: "PDW-57",
    type: "SMG",
    description: "Melhor classe para PDW-57 no COD Mobile",
    descriptionEn: "Best loadout for PDW-57 in COD Mobile",
    code: "1C2A4A5E9A",
    codePt: "1C2A4A5E9A",
    codeEn: "1C2A4A5E9A",
    image: "/attached_assets/pdw-57.jpg",
    imagePt: "/attached_assets/pdw-57.jpg",
    imageEn: "/attached_assets/pdw-57.jpg",
    keywords: ["pdw-57", "smg", "codm", "loadout"],
  },
  {
    id: "razorback",
    name: "Razorback",
    namePt: "Razorback",
    nameEn: "Razorback",
    type: "SMG",
    description: "Melhor classe para Razorback no COD Mobile",
    descriptionEn: "Best loadout for Razorback in COD Mobile",
    code: "1C2A5I6C9A",
    codePt: "1C2A5I6C9A",
    codeEn: "1C2A5I6C9A",
    image: "/attached_assets/razorback.jpg",
    imagePt: "/attached_assets/razorback.jpg",
    imageEn: "/attached_assets/razorback.jpg",
    keywords: ["razorback", "smg", "codm", "loadout"],
  },
  {
    id: "msmc",
    name: "MSMC",
    namePt: "MSMC",
    nameEn: "MSMC",
    type: "SMG",
    description: "Melhor classe para MSMC no COD Mobile",
    descriptionEn: "Best loadout for MSMC in COD Mobile",
    code: "1C2C4A6C8A",
    codePt: "1C2C4A6C8A",
    codeEn: "1C2C4A6C8A",
    image: "/attached_assets/msmc.jpg",
    imagePt: "/attached_assets/msmc.jpg",
    imageEn: "/attached_assets/msmc.jpg",
    keywords: ["msmc", "smg", "codm", "loadout"],
  },
  {
    id: "hg-40",
    name: "HG 40",
    namePt: "HG 40",
    nameEn: "HG 40",
    type: "SMG",
    description: "Melhor classe para HG 40 no COD Mobile",
    descriptionEn: "Best loadout for HG 40 in COD Mobile",
    code: "2C4A6C8C9A",
    codePt: "2C4A6C8C9A",
    codeEn: "2C4A6C8C9A",
    image: "/attached_assets/hg-40.jpg",
    imagePt: "/attached_assets/hg-40.jpg",
    imageEn: "/attached_assets/hg-40.jpg",
    keywords: ["hg-40", "smg", "codm", "loadout"],
  },
  {
    id: "pharo",
    name: "Pharo",
    namePt: "Pharo",
    nameEn: "Pharo",
    type: "SMG",
    description: "Melhor classe para Pharo no COD Mobile",
    descriptionEn: "Best loadout for Pharo in COD Mobile",
    code: "1E2C4B7D8A",
    codePt: "1E2C4B7D8A",
    codeEn: "1E2C4B7D8A",
    image: "/attached_assets/pharo.jpg",
    imagePt: "/attached_assets/pharo.jpg",
    imageEn: "/attached_assets/pharo.jpg",
    keywords: ["pharo", "smg", "codm", "loadout"],
  },
  {
    id: "gks-2",
    name: "GKS",
    namePt: "GKS",
    nameEn: "GKS",
    type: "SMG",
    description: "Melhor classe para GKS no COD Mobile",
    descriptionEn: "Best loadout for GKS in COD Mobile",
    code: "1A2A4B6B",
    codePt: "1A2A4B6B",
    codeEn: "1A2A4B6B",
    image: "/attached_assets/gks.jpg",
    imagePt: "/attached_assets/gks.jpg",
    imageEn: "/attached_assets/gks.jpg",
    keywords: ["gks", "smg", "codm", "loadout"],
  },
  {
    id: "cordite",
    name: "Cordite",
    namePt: "Cordite",
    nameEn: "Cordite",
    type: "SMG",
    description: "Melhor classe para Cordite no COD Mobile",
    descriptionEn: "Best loadout for Cordite in COD Mobile",
    code: "1C2A4A6C8B",
    codePt: "1C2A4A6C8B",
    codeEn: "1C2A4A6C8B",
    image: "/attached_assets/cordite.jpg",
    imagePt: "/attached_assets/cordite.jpg",
    imageEn: "/attached_assets/cordite.jpg",
    keywords: ["cordite", "smg", "codm", "loadout"],
  },
  {
    id: "qq9",
    name: "QQ9",
    namePt: "QQ9",
    nameEn: "QQ9",
    type: "SMG",
    description: "Melhor classe para QQ9 no COD Mobile",
    descriptionEn: "Best loadout for QQ9 in COD Mobile",
    code: "1C2C4A6C8A",
    codePt: "1C2C4A6C8A",
    codeEn: "1C2C4A6C8A",
    image: "/attached_assets/qq9.jpg",
    imagePt: "/attached_assets/qq9.jpg",
    imageEn: "/attached_assets/qq9.jpg",
    keywords: ["qq9", "smg", "codm", "loadout"],
  },
  {
    id: "fennec",
    name: "Fennec",
    namePt: "Fennec",
    nameEn: "Fennec",
    type: "SMG",
    description: "Melhor classe para Fennec no COD Mobile",
    descriptionEn: "Best loadout for Fennec in COD Mobile",
    code: "1C2C4D7C8A",
    codePt: "1C2C4D7C8A",
    codeEn: "1C2C4D7C8A",
    image: "/attached_assets/fennec.jpg",
    imagePt: "/attached_assets/fennec.jpg",
    imageEn: "/attached_assets/fennec.jpg",
    keywords: ["fennec", "smg", "codm", "loadout"],
  },
  {
    id: "agr-556-2",
    name: "AGR 556",
    namePt: "AGR 556",
    nameEn: "AGR 556",
    type: "SMG",
    description: "Melhor classe para AGR 556 no COD Mobile",
    descriptionEn: "Best loadout for AGR 556 in COD Mobile",
    code: "1C2B4C6C8C",
    codePt: "1C2B4C6C8C",
    codeEn: "1C2B4C6C8C",
    image: "/attached_assets/agr-556.jpg",
    imagePt: "/attached_assets/agr-556.jpg",
    imageEn: "/attached_assets/agr-556.jpg",
    keywords: ["agr-556", "smg", "codm", "loadout"],
  },
  {
    id: "qxr",
    name: "QXR",
    namePt: "QXR",
    nameEn: "QXR",
    type: "SMG",
    description: "Melhor classe para QXR no COD Mobile",
    descriptionEn: "Best loadout for QXR in COD Mobile",
    code: "1C2C4A5I8A",
    codePt: "1C2C4A5I8A",
    codeEn: "1C2C4A5I8A",
    image: "/attached_assets/qxr.jpg",
    imagePt: "/attached_assets/qxr.jpg",
    imageEn: "/attached_assets/qxr.jpg",
    keywords: ["qxr", "smg", "codm", "loadout"],
  },
  {
    id: "pp19-bizon-2",
    name: "PP19 Bizon",
    namePt: "PP19 Bizon",
    nameEn: "PP19 Bizon",
    type: "SMG",
    description: "Melhor classe para PP19 Bizon no COD Mobile",
    descriptionEn: "Best loadout for PP19 Bizon in COD Mobile",
    code: "1C2B4A6C9A",
    codePt: "1C2B4A6C9A",
    codeEn: "1C2B4A6C9A",
    image: "/attached_assets/pp19-bizon.jpg",
    imagePt: "/attached_assets/pp19-bizon.jpg",
    imageEn: "/attached_assets/pp19-bizon.jpg",
    keywords: ["pp19-bizon", "smg", "codm", "loadout"],
  },
  {
    id: "cbr4",
    name: "CBR4",
    namePt: "CBR4",
    nameEn: "CBR4",
    type: "SMG",
    description: "Melhor classe para CBR4 no COD Mobile",
    descriptionEn: "Best loadout for CBR4 in COD Mobile",
    code: "1A2B4A5E9A",
    codePt: "1A2B4A5E9A",
    codeEn: "1A2B4A5E9A",
    image: "/attached_assets/cbr4.jpg",
    imagePt: "/attached_assets/cbr4.jpg",
    imageEn: "/attached_assets/cbr4.jpg",
    keywords: ["cbr4", "smg", "codm", "loadout"],
  },
  {
    id: "ppsh-41",
    name: "PPSh-41",
    namePt: "PPSh-41",
    nameEn: "PPSh-41",
    type: "SMG",
    description: "Melhor classe para PPSh-41 no COD Mobile",
    descriptionEn: "Best loadout for PPSh-41 in COD Mobile",
    code: "1C2B5E6B9B",
    codePt: "1C2B5E6B9B",
    codeEn: "1C2B5E6B9B",
    image: "/attached_assets/ppsh-41.jpg",
    imagePt: "/attached_assets/ppsh-41.jpg",
    imageEn: "/attached_assets/ppsh-41.jpg",
    keywords: ["ppsh-41", "smg", "codm", "loadout"],
  },
  {
    id: "mac-10",
    name: "MAC-10",
    namePt: "MAC-10",
    nameEn: "MAC-10",
    type: "SMG",
    description: "Melhor classe para MAC-10 no COD Mobile",
    descriptionEn: "Best loadout for MAC-10 in COD Mobile",
    code: "1B2A4D7B8B",
    codePt: "1B2A4D7B8B",
    codeEn: "1B2A4D7B8B",
    image: "/attached_assets/mac-10.jpg",
    imagePt: "/attached_assets/mac-10.jpg",
    imageEn: "/attached_assets/mac-10.jpg",
    keywords: ["mac-10", "smg", "codm", "loadout"],
  },
  {
    id: "ksp-45",
    name: "KSP 45",
    namePt: "KSP 45",
    nameEn: "KSP 45",
    type: "SMG",
    description: "Melhor classe para KSP 45 no COD Mobile",
    descriptionEn: "Best loadout for KSP 45 in COD Mobile",
    code: "1B2A4B7B8A",
    codePt: "1B2A4B7B8A",
    codeEn: "1B2A4B7B8A",
    image: "/attached_assets/ksp-45.jpg",
    imagePt: "/attached_assets/ksp-45.jpg",
    imageEn: "/attached_assets/ksp-45.jpg",
    keywords: ["ksp-45", "smg", "codm", "loadout"],
  },
  {
    id: "switchblade-x9-2",
    name: "Switchblade X9",
    namePt: "Switchblade X9",
    nameEn: "Switchblade X9",
    type: "SMG",
    description: "Melhor classe para Switchblade X9 no COD Mobile",
    descriptionEn: "Best loadout for Switchblade X9 in COD Mobile",
    code: "1F2C4A8A9A",
    codePt: "1F2C4A8A9A",
    codeEn: "1F2C4A8A9A",
    image: "/attached_assets/switchblade-x9.jpg",
    imagePt: "/attached_assets/switchblade-x9.jpg",
    imageEn: "/attached_assets/switchblade-x9.jpg",
    keywords: ["switchblade-x9", "smg", "codm", "loadout"],
  },
  {
    id: "lapa",
    name: "LAPA",
    namePt: "LAPA",
    nameEn: "LAPA",
    type: "SMG",
    description: "Melhor classe para LAPA no COD Mobile",
    descriptionEn: "Best loadout for LAPA in COD Mobile",
    code: "1B2F4F8B9C",
    codePt: "1B2F4F8B9C",
    codeEn: "1B2F4F8B9C",
    image: "/attached_assets/lapa.jpg",
    imagePt: "/attached_assets/lapa.jpg",
    imageEn: "/attached_assets/lapa.jpg",
    keywords: ["lapa", "smg", "codm", "loadout"],
  },
  {
    id: "ots-9",
    name: "OTs 9",
    namePt: "OTs 9",
    nameEn: "OTs 9",
    type: "SMG",
    description: "Melhor classe para OTs 9 no COD Mobile",
    descriptionEn: "Best loadout for OTs 9 in COD Mobile",
    code: "1B2B7F8B9B",
    codePt: "1B2B7F8B9B",
    codeEn: "1B2B7F8B9B",
    image: "/attached_assets/ots-9.jpg",
    imagePt: "/attached_assets/ots-9.jpg",
    imageEn: "/attached_assets/ots-9.jpg",
    keywords: ["ots-9", "smg", "codm", "loadout"],
  },
  {
    id: "striker-45",
    name: "Striker 45",
    namePt: "Striker 45",
    nameEn: "Striker 45",
    type: "SMG",
    description: "Melhor classe para Striker 45 no COD Mobile",
    descriptionEn: "Best loadout for Striker 45 in COD Mobile",
    code: "1C2C6C7C8A",
    codePt: "1C2C6C7C8A",
    codeEn: "1C2C6C7C8A",
    image: "/attached_assets/striker-45.jpg",
    imagePt: "/attached_assets/striker-45.jpg",
    imageEn: "/attached_assets/striker-45.jpg",
    keywords: ["striker-45", "smg", "codm", "loadout"],
  },
  {
    id: "tec-9",
    name: "TEC-9",
    namePt: "TEC-9",
    nameEn: "TEC-9",
    type: "SMG",
    description: "Melhor classe para TEC-9 no COD Mobile",
    descriptionEn: "Best loadout for TEC-9 in COD Mobile",
    code: "1F2E4B8F9A",
    codePt: "1F2E4B8F9A",
    codeEn: "1F2E4B8F9A",
    image: "/attached_assets/tec-9.jpg",
    imagePt: "/attached_assets/tec-9.jpg",
    imageEn: "/attached_assets/tec-9.jpg",
    keywords: ["tec-9", "smg", "codm", "loadout"],
  },
  {
    id: "mx9-2",
    name: "MX9",
    namePt: "MX9",
    nameEn: "MX9",
    type: "SMG",
    description: "Melhor classe para MX9 no COD Mobile",
    descriptionEn: "Best loadout for MX9 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/mx9.jpg",
    imagePt: "/attached_assets/mx9.jpg",
    imageEn: "/attached_assets/mx9.jpg",
    keywords: ["mx9", "smg", "codm", "loadout"],
  },
  {
    id: "cbr4-2",
    name: "CBR4",
    namePt: "CBR4",
    nameEn: "CBR4",
    type: "SMG",
    description: "Melhor classe para CBR4 no COD Mobile",
    descriptionEn: "Best loadout for CBR4 in COD Mobile",
    code: "1A2B4A5E9A",
    codePt: "1A2B4A5E9A",
    codeEn: "1A2B4A5E9A",
    image: "/attached_assets/cbr4.jpg",
    imagePt: "/attached_assets/cbr4.jpg",
    imageEn: "/attached_assets/cbr4.jpg",
    keywords: ["cbr4", "smg", "codm", "loadout"],
  },
  {
    id: "ak-47-2",
    name: "AK-47",
    namePt: "AK-47",
    nameEn: "AK-47",
    type: "Assault Rifle",
    description: "Melhor classe para AK-47 no COD Mobile",
    descriptionEn: "Best loadout for AK-47 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/ak-47.jpg",
    imagePt: "/attached_assets/ak-47.jpg",
    imageEn: "/attached_assets/ak-47.jpg",
    keywords: ["ak-47", "assault rifle", "codm", "loadout"],
  },
  {
    id: "m13-2",
    name: "M13",
    namePt: "M13",
    nameEn: "M13",
    type: "Assault Rifle",
    description: "Melhor classe para M13 no COD Mobile",
    descriptionEn: "Best loadout for M13 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/m13.jpg",
    imagePt: "/attached_assets/m13.jpg",
    imageEn: "/attached_assets/m13.jpg",
    keywords: ["m13", "assault rifle", "codm", "loadout"],
  },
  {
    id: "kilo-141-2",
    name: "Kilo 141",
    namePt: "Kilo 141",
    nameEn: "Kilo 141",
    type: "Assault Rifle",
    description: "Melhor classe para Kilo 141 no COD Mobile",
    descriptionEn: "Best loadout for Kilo 141 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/kilo-141.jpg",
    imagePt: "/attached_assets/kilo-141.jpg",
    imageEn: "/attached_assets/kilo-141.jpg",
    keywords: ["kilo-141", "assault rifle", "codm", "loadout"],
  },
  {
    id: "m4-2",
    name: "M4",
    namePt: "M4",
    nameEn: "M4",
    type: "Assault Rifle",
    description: "Melhor classe para M4 no COD Mobile",
    descriptionEn: "Best loadout for M4 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/m4.jpg",
    imagePt: "/attached_assets/m4.jpg",
    imageEn: "/attached_assets/m4.jpg",
    keywords: ["m4", "assault rifle", "codm", "loadout"],
  },
  {
    id: "dr-h-2",
    name: "DR-H",
    namePt: "DR-H",
    nameEn: "DR-H",
    type: "Assault Rifle",
    description: "Melhor classe para DR-H no COD Mobile",
    descriptionEn: "Best loadout for DR-H in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/dr-h.jpg",
    imagePt: "/attached_assets/dr-h.jpg",
    imageEn: "/attached_assets/dr-h.jpg",
    keywords: ["dr-h", "assault rifle", "codm", "loadout"],
  },
  {
    id: "hvk-30-2",
    name: "HVK-30",
    namePt: "HVK-30",
    nameEn: "HVK-30",
    type: "Assault Rifle",
    description: "Melhor classe para HVK-30 no COD Mobile",
    descriptionEn: "Best loadout for HVK-30 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/hvk-30.jpg",
    imagePt: "/attached_assets/hvk-30.jpg",
    imageEn: "/attached_assets/hvk-30.jpg",
    keywords: ["hvk-30", "assault rifle", "codm", "loadout"],
  },
  {
    id: "kn-44-2",
    name: "KN-44",
    namePt: "KN-44",
    nameEn: "KN-44",
    type: "Assault Rifle",
    description: "Melhor classe para KN-44 no COD Mobile",
    descriptionEn: "Best loadout for KN-44 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/kn-44.jpg",
    imagePt: "/attached_assets/kn-44.jpg",
    imageEn: "/attached_assets/kn-44.jpg",
    keywords: ["kn-44", "assault rifle", "codm", "loadout"],
  },
  {
    id: "icr-1-2",
    name: "ICR-1",
    namePt: "ICR-1",
    nameEn: "ICR-1",
    type: "Assault Rifle",
    description: "Melhor classe para ICR-1 no COD Mobile",
    descriptionEn: "Best loadout for ICR-1 in COD Mobile",
    code: "1F4B5A6A8A",
    codePt: "1F4B5A6A8A",
    codeEn: "1F4B5A6A8A",
    image: "/attached_assets/icr-1.jpg",
    imagePt: "/attached_assets/icr-1.jpg",
    imageEn: "/attached_assets/icr-1.jpg",
    keywords: ["icr-1", "assault rifle", "codm", "loadout"],
  },
  {
    id: "man-o-war-2",
    name: "Man-O-War",
    namePt: "Man-O-War",
    nameEn: "Man-O-War",
    type: "Assault Rifle",
    description: "Melhor classe para Man-O-War no COD Mobile",
    descriptionEn: "Best loadout for Man-O-War in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/man-o-war.jpg",
    imagePt: "/attached_assets/man-o-war.jpg",
    imageEn: "/attached_assets/man-o-war.jpg",
    keywords: ["man-o-war", "assault rifle", "codm", "loadout"],
  },
  {
    id: "as-val-2",
    name: "AS VAL",
    namePt: "AS VAL",
    nameEn: "AS VAL",
    type: "Assault Rifle",
    description: "Melhor classe para AS VAL no COD Mobile",
    descriptionEn: "Best loadout for AS VAL in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/as-val.jpg",
    imagePt: "/attached_assets/as-val.jpg",
    imageEn: "/attached_assets/as-val.jpg",
    keywords: ["as-val", "assault rifle", "codm", "loadout"],
  },
  {
    id: "bk57-2",
    name: "BK57",
    namePt: "BK57",
    nameEn: "BK57",
    type: "Assault Rifle",
    description: "Melhor classe para BK57 no COD Mobile",
    descriptionEn: "Best loadout for BK57 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/bk57.jpg",
    imagePt: "/attached_assets/bk57.jpg",
    imageEn: "/attached_assets/bk57.jpg",
    keywords: ["bk57", "assault rifle", "codm", "loadout"],
  },
  {
    id: "lk24-2",
    name: "LK24",
    namePt: "LK24",
    nameEn: "LK24",
    type: "Assault Rifle",
    description: "Melhor classe para LK24 no COD Mobile",
    descriptionEn: "Best loadout for LK24 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/lk24.jpg",
    imagePt: "/attached_assets/lk24.jpg",
    imageEn: "/attached_assets/lk24.jpg",
    keywords: ["lk24", "assault rifle", "codm", "loadout"],
  },
  {
    id: "peacekeeper-mk2-2",
    name: "Peacekeeper MK2",
    namePt: "Peacekeeper MK2",
    nameEn: "Peacekeeper MK2",
    type: "Assault Rifle",
    description: "Melhor classe para Peacekeeper MK2 no COD Mobile",
    descriptionEn: "Best loadout for Peacekeeper MK2 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/peacekeeper-mk2.jpg",
    imagePt: "/attached_assets/peacekeeper-mk2.jpg",
    imageEn: "/attached_assets/peacekeeper-mk2.jpg",
    keywords: ["peacekeeper-mk2", "assault rifle", "codm", "loadout"],
  },
  {
    id: "fr-5-56-2",
    name: "FR 5.56",
    namePt: "FR 5.56",
    nameEn: "FR 5.56",
    type: "Assault Rifle",
    description: "Melhor classe para FR 5.56 no COD Mobile",
    descriptionEn: "Best loadout for FR 5.56 in COD Mobile",
    code: "1C2B4A6C8C",
    codePt: "1C2B4A6C8C",
    codeEn: "1C2B4A6C8C",
    image: "/attached_assets/fr-5-56.jpg",
    imagePt: "/attached_assets/fr-5-56.jpg",
    imageEn: "/attached_assets/fr-5-56.jpg",
    keywords: ["fr-5-56", "assault rifle", "codm", "loadout"],
  },
  {
    id: "hbra3-2",
    name: "HBRa3",
    namePt: "HBRa3",
    nameEn: "HBRa3",
    type: "Assault Rifle",
    description: "Melhor classe para HBRa3 no COD Mobile",
    descriptionEn: "Best loadout for HBRa3 in COD Mobile",
    code: "1B2B4C5E9A",
    codePt: "1B2B4C5E9A",
    codeEn: "1B2B4C5E9A",
    image: "/attached_assets/hbra3.jpg",
    imagePt: "/attached_assets/hbra3.jpg",
    imageEn: "/attached_assets/hbra3.jpg",
    keywords: ["hbra3", "assault rifle", "codm", "loadout"],
  },
  {
    id: "ak117-2",
    name: "AK117",
    namePt: "AK117",
    nameEn: "AK117",
    type: "Assault Rifle",
    description: "Melhor classe para AK117 no COD Mobile",
    descriptionEn: "Best loadout for AK117 in COD Mobile",
    code: "2B4A7E8B9F",
    codePt: "2B4A7E8B9F",
    codeEn: "2B4A7E8B9F",
    image: "/attached_assets/ak117.jpg",
    imagePt: "/attached_assets/ak117.jpg",
    imageEn: "/attached_assets/ak117.jpg",
    keywords: ["ak117", "assault rifle", "codm", "loadout"],
  },
  {
    id: "type-25-2",
    name: "Type 25",
    namePt: "Type 25",
    nameEn: "Type 25",
    type: "Assault Rifle",
    description: "Melhor classe para Type 25 no COD Mobile",
    descriptionEn: "Best loadout for Type 25 in COD Mobile",
    code: "2A6C7A8A9A",
    codePt: "2A6C7A8A9A",
    codeEn: "2A6C7A8A9A",
    image: "/attached_assets/type-25.jpg",
    imagePt: "/attached_assets/type-25.jpg",
    imageEn: "/attached_assets/type-25.jpg",
    keywords: ["type-25", "assault rifle", "codm", "loadout"],
  },
  {
    id: "asm10-2",
    name: "ASM10",
    namePt: "ASM10",
    nameEn: "ASM10",
    type: "Assault Rifle",
    description: "Melhor classe para ASM10 no COD Mobile",
    descriptionEn: "Best loadout for ASM10 in COD Mobile",
    code: "1E6B7A8B9C",
    codePt: "1E6B7A8B9C",
    codeEn: "1E6B7A8B9C",
    image: "/attached_assets/asm10.jpg",
    imagePt: "/attached_assets/asm10.jpg",
    imageEn: "/attached_assets/asm10.jpg",
    keywords: ["asm10", "assault rifle", "codm", "loadout"],
  },
  {
    id: "dl-q33-2",
    name: "DL Q33",
    namePt: "DL Q33",
    nameEn: "DL Q33",
    type: "Sniper",
    description: "Melhor classe para DL Q33 no COD Mobile",
    descriptionEn: "Best loadout for DL Q33 in COD Mobile",
    code: "1C4C6C7C8A",
    codePt: "1C4C6C7C8A",
    codeEn: "1C4C6C7C8A",
    image: "/attached_assets/dl-q33.jpg",
    imagePt: "/attached_assets/dl-q33.jpg",
    imageEn: "/attached_assets/dl-q33.jpg",
    keywords: ["dl-q33", "sniper", "codm", "loadout"],
  },
  {
    id: "locus-3",
    name: "Locus",
    namePt: "Locus",
    nameEn: "Locus",
    type: "Sniper",
    description: "Melhor classe para Locus no COD Mobile",
    descriptionEn: "Best loadout for Locus in COD Mobile",
    code: "1B2C4A5A7C",
    codePt: "1B2C4A5A7C",
    codeEn: "1B2C4A5A7C",
    image: "/attached_assets/locus.jpg",
    imagePt: "/attached_assets/locus.jpg",
    imageEn: "/attached_assets/locus.jpg",
    keywords: ["locus", "sniper", "codm", "loadout"],
  },
  {
    id: "arctic-50-2",
    name: "Arctic .50",
    namePt: "Arctic .50",
    nameEn: "Arctic .50",
    type: "Sniper",
    description: "Melhor classe para Arctic .50 no COD Mobile",
    descriptionEn: "Best loadout for Arctic .50 in COD Mobile",
    code: "1B2B4A8B9F",
    codePt: "1B2B4A8B9F",
    codeEn: "1B2B4A8B9F",
    image: "/attached_assets/arctic-50.jpg",
    imagePt: "/attached_assets/arctic-50.jpg",
    imageEn: "/attached_assets/arctic-50.jpg",
    keywords: ["arctic-50", "sniper", "codm", "loadout"],
  },
  {
    id: "koshka-3",
    name: "Koshka",
    namePt: "Koshka",
    nameEn: "Koshka",
    type: "Sniper",
    description: "Melhor classe para Koshka no COD Mobile",
    descriptionEn: "Best loadout for Koshka in COD Mobile",
    code: "1B2B6C7C9B",
    codePt: "1B2B6C7C9B",
    codeEn: "1B2B6C7C9B",
    image: "/attached_assets/koshka.jpg",
    imagePt: "/attached_assets/koshka.jpg",
    imageEn: "/attached_assets/koshka.jpg",
    keywords: ["koshka", "sniper", "codm", "loadout"],
  },
  {
    id: "zrg-20mm-2",
    name: "ZRG 20mm",
    namePt: "ZRG 20mm",
    nameEn: "ZRG 20mm",
    type: "Sniper",
    description: "Melhor classe para ZRG 20mm no COD Mobile",
    descriptionEn: "Best loadout for ZRG 20mm in COD Mobile",
    code: "1A2B7D8A9I",
    codePt: "1A2B7D8A9I",
    codeEn: "1A2B7D8A9I",
    image: "/attached_assets/zrg-20mm.jpg",
    imagePt: "/attached_assets/zrg-20mm.jpg",
    imageEn: "/attached_assets/zrg-20mm.jpg",
    keywords: ["zrg-20mm", "sniper", "codm", "loadout"],
  },
  {
    id: "sks-2",
    name: "SKS",
    namePt: "SKS",
    nameEn: "SKS",
    type: "Marksman",
    description: "Melhor classe para SKS no COD Mobile",
    descriptionEn: "Best loadout for SKS in COD Mobile",
    code: "1D2C5F7B8B",
    codePt: "1D2C5F7B8B",
    codeEn: "1D2C5F7B8B",
    image: "/attached_assets/sks.jpg",
    imagePt: "/attached_assets/sks.jpg",
    imageEn: "/attached_assets/sks.jpg",
    keywords: ["sks", "marksman", "codm", "loadout"],
  },
  {
    id: "mk2-2",
    name: "MK2",
    namePt: "MK2",
    nameEn: "MK2",
    type: "Marksman",
    description: "Melhor classe para MK2 no COD Mobile",
    descriptionEn: "Best loadout for MK2 in COD Mobile",
    code: "1C2B6C7A8B",
    codePt: "1C2B6C7A8B",
    codeEn: "1C2B6C7A8B",
    image: "/attached_assets/mk2.jpg",
    imagePt: "/attached_assets/mk2.jpg",
    imageEn: "/attached_assets/mk2.jpg",
    keywords: ["mk2", "marksman", "codm", "loadout"],
  },
];
